### PR TITLE
Support for mutiple portals and new React context

### PR DESCRIPTION
**Pull request by kokusGr**
Hi :)

I have been using your library for quite some time and would like to contribute. This PR adds:
- support for more than one portal of the same `name` open at the same time. This can be used to create nested sub menus on web for example
- support for new React context API.

Please let me know if this is some you are interested in and what can I do to make it better

EDIT: I changed storing portal values for backward compatibility and make it more resilient to out of order unmounting.

### CODE REVIEW

**Comment by zenyr** [comment]
Heyy, thanks for the PR and sorry for my late response, I've been using a different corporate account for work. 😭 

While I appreciate this PR but I think this warrants a major version bump due to change in behavior. And I'd like to add some accompanying tests to clarify its behavior. 

Oh and I should also check my npm credentials too.. 👀

**Comment by andrewzey** [comment]
Thank you @kokusGr 

!This PR also fixes the following bug when using `react-native-portal` with modals and `react-navigation` 3.x:

screen shot 2019-03-03 at 7 25 48 pm

I encountered it in the following scenario:

When both screens A and B have a BlackPortal targeting the same WhitePortal, opening the model on Screen A, navigating to screen B, opening the modal on screen B, then popping B off the stack and navigating back to Screen A, I encountered the error message screenshotted above.

I presume, though I haven't investigated deeply, that the ref was unmounted from the WhitePoral when popping off screen B. Workaround could have been to force a re-render on `react-navigation` didFocus event, but I simply copied @kokusGr 's repo locally for the time being, and found the issue was completely resolved. I haven't dug deeper yet as I'm on a deadline (who isn't!), but it would be great if we could get this merged in, and I could go back to using the published package instead of copy-pasta'd code in our project.

Screen A and B Portal usage...
```
<BlackPortal name="modal">
   <CardModal ref={ref => (this.confirmModal = getInnermostRef(ref))}>
...

```

Is there anything I can do to help get this merged in?

**Comment by jramalho** [comment]
This lib will trigger the remount of the component?

**Comment by kokusGr** [comment]
@zenyr thanks for the reply and sorry for inactivity, it was a hectic period. What can I do to make this PR better? :)

@andrewzey wow that's nice. I don't use `react-navigation` but I am glad that my changes helped :)

**Comment by radex** [comment]
@zenyr what can we do to move this PR forward?

**Comment by rafalolszewski94** [comment]
Bumping what @radex said, would be nice to merge this.

Also I'd export `PortalContext` for the sake of `useContext` hook inside of function components.

**Comment by jpalumickas** [comment]
Hey!

Any news when this will be ready to merge?

**Comment by kokusGr** [comment]
Closing since author deprecated this library. You can find version with above changes here: https://github.com/Nozbe/react-native-portal

**Pull request closed without merging**
